export const routeNames = {
    main: '/',
    captcha: '/anti-captcha',
    groups: '/groups',
    group: '/group',
    monitoring: '/monitoring',
    positions: '/positions',
    settings: '/settings',
    versions: '/versions',
    projects: '/projects',
    project: '/project-page',
    networks: '/networks',
    map: '/top-visor.html',
    yandexAccounts: '/yandexAccounts',
}
